### PR TITLE
ZF optimisations

### PR DESCRIPTION
**Pull request by pjt33**
A total of 34 states saved by various micro-optimisations.

### CODE REVIEW

**Comment by sorear** [comment]
FYI, `unpair` needs a bit more love, it's broken in the `out2 = t0` case, which is used by `car()`

**Comment by pjt33** [comment]
@sorear Introducing a new temp variable and using that and `t1` in `unpair` is safe. It increases the number of states to 1906, though.

**Comment by pjt33** [comment]
1905:

```
@@ -43,8 +43,8 @@ proc gproof() {
 }
 proc car() {
     pop(t2, wstack);
-    unpair(t2, t0, t2);
-    push(wstack, t2);
+    unpair(t0, t2, t2);
+    push(wstack, t0);
 }
 proc cdr() {
     pop(t2, wstack);
@@ -98,8 +98,8 @@ proc wal() {
 }

 proc wn() {
-    unpair(t4, t0, wstack);
-    push(wstack, t4);
+    unpair(t0, t4, wstack);
+    push(wstack, t0);
     t4 = 2;
     triple();
 }
@@ -165,7 +165,7 @@ proc wa() { /* ( ph /\ ps ) == -. ( ph -> -. ps ) */

 proc wb() { /* ( ph <-> ps ) == ( ( ph -> ps ) /\ ( ps -> ph ) ) */
     unpair(t6, t7, wstack); /* t6=tos=ps */
-    unpair(t7, t0, t7); /* t7=ntos=ph */
+    unpair(t0, t7, t7); t7=t0; /* t7=ntos=ph */
     wi();
     pair(wstack, t7, wstack);
     pair(wstack, t6, wstack);
@@ -180,7 +180,7 @@ proc verify() {
     /* wstack in: proof  stack out: wff that was proved, may set valid=0 */
     /* get the opcode/axiom number */
     pop(proof, wstack);
-    unpair(t2, t0, proof);
+    unpair(t0, t2, proof); t2 = t0;

     /* axioms from:
        http://us.metamath.org/mpegif/mmset.html

```

**Comment by pjt33** [comment]
1902:

```
@@ -10,16 +10,17 @@ proc pair(out, in1, in2) {
 }

 proc unpair(out1, out2, in) {
+    /* NB out2 can be aliased to t0 */
+    /* NB out1 can be aliased to in */
     t0 = 0;
     t1 = 0; /* invariant: t1 = t0 * (t0 + 1) / 2 */
     while (in >= t1) {
         t0 = t0 + 1;
         t1 = t1 + t0;
     }
-    t1 = t1 - t0;
     t0 = t0 - 1;
-    out2 = in - t1;
-    out1 = t0 - out2;
+    out1 = t1 - in;
+    out2 = t0 - out1;
 }

 proc push(stack, var) { pair(stack, var, stack); }
@@ -48,8 +49,8 @@ proc car() {
 }
 proc cdr() {
     pop(t2, wstack);
-    unpair(t0, t2, t2);
-    push(wstack, t2);
+    unpair(t2, t0, t2);
+    push(wstack, t0);
 }
 proc cddr() { cdr(); cdr(); }
 proc cadr() { cdr(); car(); }

```

**Pull request merged**
